---
title: "Class activity work"
---

## Class activity 1 - 09/19

-   MSSC 5780 Presenters: [David Aguilera](activity/act-1_david.pptx), Rachel Cutlan

-   MATH 4780 Questioners: Ethan Baierl, Patrick Campbell, Dylan Cardoza

## Class activity 2 - 09/26

-   MSSC 5780 Presenters: Timothy Goodwin, Matt Jaeggin

-   MATH 4780 Questioners: Huangkun Chen, Davion Cook, Nicky Diaz

## Class activity 3 - 10/10

-   MSSC 5780 Presenters: Samantha Juedemann, Edward Liu

-   MATH 4780 Questioners: Nathan Fisher, Alberto Gamez Gonzalez, Andrew Hiller

## Class activity 4 - 10/24

-   MSSC 5780 Presenters: Sylvester Mensah, Navid Mohseni

-   MATH 4780 Questioners: Jake Konrad, Vanessa Lattas, Danny O'Shea

## Class activity 5 - 11/14

-   MSSC 5780 Presenters: Emmanuel Nyamekye, Adam Reeson

-   MATH 4780 Questioners: Kayley Reith, Donny Robbins, Ray Sun

## Class activity 6 - 12/05

-   MSSC 5780 Presenters: Anesti Sotirovski, Tanjina Zaman

-   MATH 4780 Questioners: Violet Wang, T.J. James Whapham II, Serena Yang
