---
title: "MATH 4780 - Regression Analysis"
tbl-colwidths: [5,10,30,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
|           Week            | Date        | Topic                                                                                                                     |                             Prepare                             |                                                                           Slides                                                                            |                                    Lab                                     | HW  |                                                                                                                                                                                                                                                                                                                       Project                                                                                                                                                                                                                                                                                                                        |
|:----:|------|------|:----:|:----:|:----:|:----:|:---------------------------:|
|  [1](/weeks/week-1.html)  | Tue, Aug 29 | Greetings + Overview of Regression                                                                                        |  [📖](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  | [🖥️](/slides/01-syllabus.html "01-syllabus"){aria-label="01-syllabus slides"} [🖥️](/slides/02-overview.html "02-overview"){aria-label="02-overview slides"} |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Aug 31 | Probability and Statistics Review                                                                                         |                                                                 |                                      [🖥️](/slides/lec-1.html "03-prob-stat slides"){aria-label="03-prob-stat slides"}                                       |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [2](/weeks/week-2.html)  | Tue, Sep 5  | Simple Linear Regression (SLR)                                                                                            |                                                                 |                                              [🖥️](/slides/lab-1.html "Lab slides"){aria-label="Lab 1 slides"}                                               | [💻](/labs/lab-1.html "Lab instructions"){aria-label="Lab 1 instructions"} |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Sep 7  | Simple Linear Regression                                                                                                  |                                                                 |                                          [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}                                           |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [3](/weeks/week-3.html)  | Tue, Sep 12 | Simple Linear Regression                                                                                                  |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Sep 14 | Simple Linear Regression                                                                                                  |  [📖](/weeks/week-3.html#prepare){aria-label="Week 3 summary"}  |                                          [🖥️](/slides/lec-4.html "Lecture slides"){aria-label="Lecture 4 slides"}                                           |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [4](/weeks/week-4.html)  | Tue, Sep 19 | Multiple Linear Regression                                                                                                |                                                                 |                                               [🖥️](/slides/lab-2.pdf "Lab slides"){aria-label="Lab 2 slides"}                                               | [💻](/labs/lab-2.html "Lab instructions"){aria-label="Lab 2 instructions"} |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Sep 21 | Multiple Linear Regression                                                                                                |  [📖](/weeks/week-4.html#prepare){aria-label="Week 4 summary"}  |                                          [🖥️](/slides/lec-6.html "Lecture slides"){aria-label="Lecture 6 slides"}                                           |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [5](/weeks/week-5.html)  | Tue, Sep 26 | Multiple Linear Regression                                                                                                |                                                                 |                                              [🖥️](/slides/lab-3.html "Lab slides"){aria-label="Lab 3 slides"}                                               | [💻](/labs/lab-3.html "Lab instructions"){aria-label="Lab 3 instructions"} |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Sep 28 | Multiple Linear Regression                                                                                                |  [📖](/weeks/week-5.html#prepare){aria-label="Week 5 summary"}  |                                          [🖥️](/slides/lec-8.html "Lecture slides"){aria-label="Lecture 8 slides"}                                           |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [6](/weeks/week-6.html)  | Tue, Oct 3  | Diagnostics: Residuals                                                                                                    |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Oct 5  | Diagnostics: Unusual Data                                                                                                 |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [7](/weeks/week-7.html)  | Tue, Oct 10 | Diagnostics: Symmetry and Normality                                                                                       |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                                  [📂](https://sta210-s22.github.io/website/project-description.html#topic-ideas){aria-label="Project topic ideas"}                                                                                                                                                                                                                                                                   |
|                           | Thu, Oct 12 | Diagnostics: Constant Variance                                                                                            |  [📖](/weeks/week-7.html#prepare){aria-label="Week 7 summary"}  |                                         [🖥️](/slides/lec-12.html "Lecture slides"){aria-label="Lecture 12 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [8](/weeks/week-8.html)  | Tue, Oct 17 | Diagnostics: Linearity                                                                                                    |                                                                 |                                                                                                                                                             | [💻](/labs/lab-4.html "Lab instructions"){aria-label="Lab 4 instructions"} |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Oct 19 | Diagnostics: Lack of Fit                                                                                                  |  [📖](/weeks/week-8.html#prepare){aria-label="Week 8 summary"}  |                                         [🖥️](/slides/lec-14.html "Lecture slides"){aria-label="Lecture 14 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [9](/weeks/week-9.html)  | Tue, Oct 24 | Polynomial Regression                                                                                                     |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Oct 26 | Nonparametric Regression                                                                                                  |  [📖](/weeks/week-9.html#prepare){aria-label="Week 9 summary"}  |                                         [🖥️](/slides/lec-16.html "Lecture slides"){aria-label="Lecture 16 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [10](/weeks/week-10.html) | Tue, Oct 31 | Categorical Variables                                                                                                     |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                              [📂](https://sta210-s22.github.io/website/project-description.html#project-proposal){aria-label="Project topic proposal"}                                                                                                                                                                                                                                                               |
|                           | Thu, Nov 2  | Categorical Variables                                                                                                     | [📖](/weeks/week-10.html#prepare){aria-label="Week 10 summary"} |                                         [🖥️](/slides/lec-18.html "Lecture slides"){aria-label="Lecture 18 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [11](/weeks/week-11.html) | Tue, Nov 7  | Collinearity                                                                                                              |                                                                 |                                                                                                                                                             | [💻](/labs/lab-5.html "Lab instructions"){aria-label="Lab 5 instructions"} |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Nov 9  | Collinearity                                                                                                              | [📖](/weeks/week-11.html#prepare){aria-label="Week 11 summary"} |                                         [🖥️](/slides/lec-20.html "Lecture slides"){aria-label="Lecture 20 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [12](/weeks/week-12.html) | Tue, Nov 14 | Variable Selection                                                                                                        |                                                                 |                                                                                                                                                             |                                                                            |     |                [📂](https://sta210-s22.github.io/website/project-description.html#draft-report){aria-label="Project draft report" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}                |
|                           | Thu, Nov 16 | Variable Selection                                                                                                        | [📖](/weeks/week-12.html#prepare){aria-label="Week 12 summary"} |                                         [🖥️](/slides/lec-22.html "Lecture slides"){aria-label="Lecture 22 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [13](/weeks/week-13.html) | Tue, Nov 21 |                                                                                                                           |                                                                 |                                                                                                                                                             | [💻](/labs/lab-6.html "Lab instructions"){aria-label="Lab 6 instructions"} |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Nov 23 | *NO CLASS: Thanksgiving*                                                                                                  | [📖](/weeks/week-13.html#prepare){aria-label="Week 13 summary"} |                                         [🖥️](/slides/lec-24.html "Lecture slides"){aria-label="Lecture 24 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [14](/weeks/week-14.html) | Tue, Nov 28 | Generalized Linear Model                                                                                                  |                                                                 |                                                                                                                                                             |                                                                            |     |                 [📂](https://sta210-s22.github.io/website/project-description.html#peer-review){aria-label="Project peer review" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}                 |
|                           | Thu, Nov 30 | Logistic Regression                                                                                                       | [📖](/weeks/week-14.html#prepare){aria-label="Week 14 summary"} |                                         [🖥️](/slides/lec-26.html "Lecture slides"){aria-label="Lecture 26 slides"}                                          |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [15](/weeks/week-15.html) | Tue, Dec 5  | Logistic Regression                                                                                                       |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thu, Dec 7  |                                                                                                                           |                                                                 |                                                                                                                                                             |                                                                            |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [16](/weeks/week-16.html) |             | Due: [Project write-up](https://sta210-s22.github.io/website/project-description.html#written-report)                     |                                                                 |                                                                                                                                                             |                                                                            |     |              [📂](https://sta210-s22.github.io/website/project-description.html#written-report){aria-label="Project written report" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}              |
|                           |             | Due: [Video presentation](https://sta210-s22.github.io/website/project-description.html#video-presentation-slides) + repo |                                                                 |                                                                                                                                                             |                                                                            |     | [📂](https://sta210-s22.github.io/website/project-description.html#video-presentation-slides){aria-label="Project video presentation and slides" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"} |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|-------|-------|-------|:-----:|:-----:|:-----:|:-------------:|:-----:|:-----:|:-----:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
