---
title: "Homework 6 - Collinearity and Variable Selection"
subtitle: "Due Friday, December 8, 11:59 PM on D2L"
editor: source
---


# Homework Instruction and Requirement

- Homework 6 covers course materials of Week 1 to 14.

- Please submit your work in **one** **PDF** file including all parts to **D2L > Assessments > Dropbox**. *Multiple files or a file that is not in pdf format are not allowed.*

- In your homework, please number and answer questions **in order**. 

-   Your entire work on Statistical Computing and Data Analysis should be completed by any word processing software (Microsoft Word, Google Docs, [(R)Markdown](https://rmarkdown.rstudio.com/), [Quarto](https://quarto.org/), [LaTex](https://www.latex-project.org/), etc) and your preferred programming language. Your document should be a PDF file.

<!-- - Questions starting with **(MSSC)** are for MSSC 5780 students. MATH 4780 students could possibly earn extra points from them. -->

- It is your responsibility to let me understand what you try to show. If you type your answers, make sure there are no typos. I grade your work based on *what you show, not what you want to show*. If you choose to handwrite your answers, write them neatly. If I can’t read your sloppy handwriting, your answer is judged as wrong.


# Reading and Writing (30 points for MATH 4780, and 50 points for MSSC 5780)

In this class, we have been using the [classical or frequentist approach](https://en.wikipedia.org/wiki/Frequentist_inference) to do a variety of statistical inferences, marginal $t$ test for $\beta_j$ and $F$ tests for model comparison for example. But Dr. Yu once said he never uses p-value in his own research, and there are many issues with what is taught in Intro Stats (MATH 1700/4720/4740). In fact, the null hypothesis significance testing (NHST) paradigm and the p-value usage have been much criticized and shown to be problematic, misused, and resulting in reproducibility and replication crisis in scientific research. Please write a summary paper (**at least one page for MATH 4780 and two pages for MSSC 5780**) including

  - Interpretation of p-value
  - List and discussion about the problems of the NHST and p-value method
  - Possible solutions to those problems
  
Some references are

  - [Wikipedia: Misuse of p-values](https://en.wikipedia.org/wiki/Misuse_of_p-values)
  
  - [A. Reinhart (2015), "Statistics Done Wrong", *No Starch Press*, San Francisco.](https://www.statisticsdonewrong.com/)
  
  - [R. L. Wasserstein and Nicole A. Lazar (2016), "The ASA Statement on p-Values: Context, Process, and Purpose", *The American Statistician*, 70:2, 129-133.](https://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108)
  
  - [V. Amrhein, S. Greenland and B. McShane (2019), "Retire statistical significance", *Nature*, 567, 305-307. ](https://www.nature.com/articles/d41586-019-00857-9)
  
  - [B. McShane, D. Gal, A. Gelman, C. Robert and Jennifer L. Tackett (2019), "Abandon Statistical Significance", *The American Statistician*, 73:sup1, 235-245.](https://www.tandfonline.com/doi/full/10.1080/00031305.2018.1527253)
  
  - [A. Gelamn and E. Loken (2014), "The Statistical Crisis in Science", *American Scientist*, 102, 460-465.](http://stat.columbia.edu/~gelman/research/published/ForkingPaths.pdf)
  
  - [R. L. Wasserstein, A. L. Schirm and N. A. Lazar (2019), "Moving to a World Beyond p < 0.05", *The American Statistician*, 73:sup1, 1-19.](https://www.tandfonline.com/doi/full/10.1080/00031305.2019.1583913)

  
There are lots of discussions and papers out there. You are welcome to google more resources to support your argument. The work should be entirely your effort. *You are not allowed to copy anyone's words, and you have to cite any resources you use, papers, blogs, videos, lecture notes, etc, or you violate Marquette academic misconduct policy.*



# Statistical Computing and Data Analysis


Please perform a data analysis using $\texttt{R}$ or your preferred language. **Any results should be generated by computer outputs, and your work should be done entirely by your computer. Handwriting is not allowed. Relevant code should be attached.**

We use the same data set `mpg.csv` for data analysis. For the following analysis, if any regressor contains a missing value `NA`, remove the corresponding row of the data matrix.

1. Build a linear regression model relating gasoline mileage $y$ to vehicle weight $x_{10}$ and the type of transmission $x_{11}$ (1 automatic; 0 manual). Does the type of transmission significantly affect the mileage performance?

2. Modify the model developed in (1) to include an interaction between vehicle weight and the type of transmission. What conclusions can you draw about the effect of the type of transmission on gasoline mileage? Interpret the parameters in this model.

For the following questions (3) to (7), consider all the regressors except $x_4$, $x_5$ and $x_{11}$.

+ $y$: MPG
+ $x_1$: Displacement (cubic in.)
+ $x_2$: Horsepower (ft-lb)
+ $x_3$: Torque (ft-lb)
+ $x_6$: Carburetor (barrels)
+ $x_7$: No. of transmission speeds
+ $x_8$: Overall length (in.)
+ $x_9$: Width (in.)
+ $x_{10}$: Weight (lb)

*Standardize the response and predictors* before later analysis.

<!-- Therefore, now you can treat a correlation matrix of regressors as the matrix ${\bf X}'{\bf X}$, where ${\bf X}$ is formed by the column vectors of predictors after unit length scaling. -->

3. Obtain the correlation matrix of regressors. Does it give any indication of collinearity? 

4. Calculate the variance inflation factors (VIFs). Is there any evidence of collinearity?

<!-- 5. Find the eigenvectors associated with the smallest eigenvalues of ${\mathbf X}'{\mathbf X}/(n - 1)$ or the correlation matrix of regressors. Interpret the elements of these vectors. What can you say about the source of collinearity in these data? -->

5. Find the eigenvectors associated with the smallest eigenvalues of the correlation matrix of regressors. Interpret the elements of these vectors. What can you say about the source of collinearity in these data?

<!-- 6. Compute the condition indices and variance-decomposition proportions. What statements can you make about collinearity in these data? -->

<!-- 7. Fit the ordinary multiple regression and the ridge regression. Use the ridge trace to select an appropriate value of $\delta$. Explain how the ridge regression coefficients change as the parameter $\delta$ increases. This gives you the idea of why the ridge regression is a *shrinkage* method. -->

<!-- 8. How much increase in the residual sum of squares has resulted from the -->
<!-- use of ridge regression? -->

<!-- 8. How much reduction in $R^2$ has resulted from the use of ridge regression? -->

<!-- 8. Perform a principal component regression (PCR). In fact, $\lambda_i/\sum_{j=1}^k\lambda_j$ tells us the proportion of total variation of the regreesors that are explained by the $i$-th principal component (PC). Use the fact to choose the number of PCs used in the PCR, so that the proportion of total variation explained by the chosen PCs is at least $95\%$. Compare the coefficients from ordinary least squares, ridge regression and PCR. -->


6. Use the all-possible-regressions approach to find an appropriate regression model.

7. Use stepwise regression to specify a subset regression model. Does this lead to the same model found in (6)?


